language: node_js
install:
  - "npm install"
  - "npm run lint"
  - "npm run build"
#   - "npm run test"

node_js:
  - "12"
  - "10"

notifications:
  email:
    recipients:
      - jsmith6690gmail.com
    on_success: never
    on_failure: always
